
import numpy as np


In [42]:
import numpy as np
print(np.__version__)
#np.show_config()
#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)
z = np.zeros((4,4))
#z[1:-1,1:-1] = 1
print(z)

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)
z = np.ones((4,4))
z[1:-1,1:-1] = 0
print(z)

z = np.zeros((10, 10))
print(f'memory size of this array is { z.size * z.itemsize}')
#print(np.info(np.add))
#x = np.arange(10,50)
#print(x[::-1])
#print(np.arange(9).reshape(3,3))
#print(np.random.randn(3,3,3))
#print(np.random.random((10,10,10)).mean().round(3))



1.26.0
[[0. 0. 0. 0.]
 [0. 1. 1. 0.]
 [0. 1. 1. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [1. 1. 1. 1.]]
memory size of this array is 800
